version: '3.8'

services:
  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
      - sogo
    networks:
      - mail-net
      - sogo-network
    restart: always

  # Backend service
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./docker-data/mailconf:/mail/config
    container_name: mail_service_backend
    env_file:
      - .env
    environment:
      - MAILSERVER_API_KEY=${MAILSERVER_API_KEY}
    depends_on:
      - mailserver
    networks:
      - mail-net
    restart: always

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    container_name: mail_service_frontend
    depends_on:
      - backend
    networks:
      - mail-net
    restart: always

  # Mailserver service (docker-mailserver)
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mail_server
    hostname: mail.ispmanager.cloudns.ph # <-- ЗАМЕНИТЕ НА ВАШ ДОМЕН
    environment:
      - SSL_TYPE=self-signed
      - DMS_DEBUG=0
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_FAIL2BAN=1
      - POSTFIX_REST_SERVER=true
      - POSTFIX_REST_SERVER_INITIAL_USER=admin@ispmanager.cloudns.ph
      - POSTFIX_REST_SERVER_INITIAL_PASSWORD=adminpass
    restart: always
    networks:
      - mail-net

  # SOGo services
  sogo:
    image: salvoxia/sogo:latest
    container_name: sogo
    restart: unless-stopped
    volumes:
      - sogo_data:/srv
      - ./sogo.conf:/srv/etc/sogo.conf:ro
    depends_on:
      - postgresql
      - memcached
    networks:
      - sogo-network

  postgresql:
    image: postgres:16-alpine
    container_name: sogo-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: sogo
      POSTGRES_USER: sogo
      POSTGRES_PASSWORD: dev_sogo_pass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql_data:/var/lib/postgresql/data/pgdata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - sogo-network

  memcached:
    image: memcached:alpine
    container_name: sogo-memcached
    restart: unless-stopped
    networks:
      - sogo-network

volumes:
  sogo_data:
  postgresql_data:

networks:
  mail-net:
    driver: bridge
  sogo-network:
    driver: bridge